### ISSUE TITLE
Cakeshop is taking a long time to start. Look at logs

### ISSUE THREAD

**Issue by huahuayu** [ConsenSys/quorum-wizard#102]
## env
mac os: 10.15.6
jdk: 11
quorum-wizard: 1.2.2

## problem
quick start

```bash
quorum-wizard -q
cd 3-nodes-quickstart
bash start.sh
```

get error

```text
Cakeshop is not yet listening on http
Cakeshop is taking a long time to start. Look at logs
```

but no cakeshop logs dir in qdata dir

## root cause
the root cause is cakeshop.war is use 0.11.0-J8 version, but tessera-app.jar need jdk11(refer to https://github.com/ConsenSys/quorum-wizard/issues/100) , so I use jdk11, but  cakeshop need java 8.

I checked https://github.com/ConsenSys/cakeshop/releases and download cakeshop-0.11.0.war to replace 0.11.0-J8 version, and `bash start.sh` again, and it's ok(in the second time, the first time still getting error)

**Comment by bmcd** [comment]
Same issue as #100 

The wizard looks at the output of java -version to see if you have java 8 or 11+, then it download the correct jars based on that. If you have Java 8, it will download cakeshop 0.11.0-J8 and tessera 0.10.2 (the last version that supports java 8). Java 11+ will download the latest for both.

Check to make sure the output of java -version is showing jdk 11 in the terminal window where you're generating the network, and the same for when you're about to start the network.
