### ISSUE TITLE
user don't have a choose on tessera version, there should be have an input field

### ISSUE THREAD

**Issue by huahuayu** [ConsenSys/quorum-wizard#103]
![image](https://user-images.githubusercontent.com/1725060/92067755-ad54f880-edd7-11ea-9cf5-c5bf6a5e9ebb.png)

**Comment by bmcd** [comment]
Yep, right now the versions don't automatically update when new ones come out, so that will be in the next release of the wizard. In the meantime, you can always download different versions of the jar and change the path at the top of the `start.sh` file to point to it.

Thanks!
