### ISSUE TITLE
WebSocket port mapped incorrectly in docker-compose network

### ISSUE THREAD

**Issue by benjamincburns** [ConsenSys/quorum-wizard#118]
When I build a custom network, I see that the websocket port gets mapped over to `8645` instead of `8546`. Likely this was a typo.

That is, for node1, I see:

```yaml
    ports:
      - "22000:8545"
      - "23000:8645"
      - "24000:8547"
```

Where I would expect to see:

```yaml
    ports:
      - "22000:8545"
      - "23000:8546"
      - "24000:8547"
```

**Comment by bmcd** [comment]
This was fixed in #113, although i found that some tests that were still using the old port value and a fallback default in the docker-compose definition was as well. Should be consistent everywhere after #119 

Thanks!
