### ISSUE TITLE
Generates wrong cakeshop configuration ignoring custom ips

### ISSUE THREAD

**Issue by danielporto** [ConsenSys/quorum-wizard#125]
Version 1.3.0

When passing a config.json to non-interactively generate a new network, the cakeshop.json generated maps all nodes to localhost.

example:
assume a custom config.json with 4 nodes running directly in bash (only change is the mapping of nodes to ips)
run quorum-wizard generate --config config.json
the configuration for tessera and quorum are fine. the cakeshop.json generated has all urls directed to localhost. Ports are fine though.

**Comment by bmcd** [comment]
Good catch! Looks like an easy fix, so it will be in the next release.
