### ISSUE TITLE
Can't using none in Tessera choice when install with k8s

### ISSUE THREAD

**Issue by skas9999** [ConsenSys/quorum-wizard#135]
Why when select k8s It can't choose none in Tessera choice?
![image](https://user-images.githubusercontent.com/77005912/116066151-f123a780-a6b1-11eb-9c86-cc787bb778b9.png)

**Comment by apratt3377** [comment]
Currently the Qubernetes project doesn't support running a quorum network without Tessera, so we don't provide this option yet in Wizard. There's an open issue for it in the Qubernetes project [#119](https://github.com/ConsenSys/qubernetes/issues/119)

**Comment by skas9999** [comment]
@apratt3377 Thank you so much. I will go with using helm instead.
